# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3677b067db7d4f3c5863f9d04f18cde9f16ace24178e53ecb81d580001c163f84eb71c9a04c38ee5b4ede1c8668674c890b14ccdf351e9466302b3453033d10

test:
  secret_key_base: d553f39d2e587a86d6e525be58bbcf9ad1b465afcc2a7e4ff377d24aae9199bf742448b366581d0624adc7066f81a4dcc3fb60d42d7e6841d643ddfbf603cfa5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
